/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CryptoHolding {
  'id' : bigint,
  'amountInvestedGBP' : number,
  'currentValueGBP' : number,
  'amount' : number,
  'symbol' : string,
}
export interface PortfolioMetrics {
  'totalValueGBP' : number,
  'totalGainLossGBP' : number,
  'percentageChange' : number,
}
export interface StakingReward {
  'id' : bigint,
  'rewardDate' : Time,
  'amount' : number,
  'symbol' : string,
}
export type Time = bigint;
export type TimeRange = { 'day' : null } |
  { 'month' : null } |
  { 'week' : null } |
  { 'year' : null } |
  { 'allTime' : null } |
  { 'sixMonths' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHolding' : ActorMethod<[string, number, number, number], bigint>,
  'addStakingReward' : ActorMethod<[string, number, Time], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteHolding' : ActorMethod<[bigint], undefined>,
  'deleteStakingReward' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHoldings' : ActorMethod<[], Array<CryptoHolding>>,
  'getPortfolioMetrics' : ActorMethod<[TimeRange], PortfolioMetrics>,
  'getStakingRewards' : ActorMethod<[], Array<StakingReward>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementHolding' : ActorMethod<[bigint, number, number], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateHolding' : ActorMethod<
    [bigint, string, number, number, number],
    undefined
  >,
  'updateStakingReward' : ActorMethod<
    [bigint, string, number, Time],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];