/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CryptoHolding = IDL.Record({
  'id' : IDL.Nat,
  'amountInvestedGBP' : IDL.Float64,
  'currentValueGBP' : IDL.Float64,
  'amount' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TimeRange = IDL.Variant({
  'day' : IDL.Null,
  'month' : IDL.Null,
  'week' : IDL.Null,
  'year' : IDL.Null,
  'allTime' : IDL.Null,
  'sixMonths' : IDL.Null,
});
export const PortfolioMetrics = IDL.Record({
  'totalValueGBP' : IDL.Float64,
  'totalGainLossGBP' : IDL.Float64,
  'percentageChange' : IDL.Float64,
});
export const StakingReward = IDL.Record({
  'id' : IDL.Nat,
  'rewardDate' : Time,
  'amount' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHolding' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addStakingReward' : IDL.Func([IDL.Text, IDL.Float64, Time], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteHolding' : IDL.Func([IDL.Nat], [], []),
  'deleteStakingReward' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Vec(CryptoHolding)], ['query']),
  'getPortfolioMetrics' : IDL.Func([TimeRange], [PortfolioMetrics], ['query']),
  'getStakingRewards' : IDL.Func([], [IDL.Vec(StakingReward)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementHolding' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateHolding' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateStakingReward' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, Time],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CryptoHolding = IDL.Record({
    'id' : IDL.Nat,
    'amountInvestedGBP' : IDL.Float64,
    'currentValueGBP' : IDL.Float64,
    'amount' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TimeRange = IDL.Variant({
    'day' : IDL.Null,
    'month' : IDL.Null,
    'week' : IDL.Null,
    'year' : IDL.Null,
    'allTime' : IDL.Null,
    'sixMonths' : IDL.Null,
  });
  const PortfolioMetrics = IDL.Record({
    'totalValueGBP' : IDL.Float64,
    'totalGainLossGBP' : IDL.Float64,
    'percentageChange' : IDL.Float64,
  });
  const StakingReward = IDL.Record({
    'id' : IDL.Nat,
    'rewardDate' : Time,
    'amount' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHolding' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addStakingReward' : IDL.Func([IDL.Text, IDL.Float64, Time], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteHolding' : IDL.Func([IDL.Nat], [], []),
    'deleteStakingReward' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Vec(CryptoHolding)], ['query']),
    'getPortfolioMetrics' : IDL.Func(
        [TimeRange],
        [PortfolioMetrics],
        ['query'],
      ),
    'getStakingRewards' : IDL.Func([], [IDL.Vec(StakingReward)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementHolding' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateHolding' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateStakingReward' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };